# Generated by Django 5.0.2 on 2024-03-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica6_rosario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arboles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tamaño', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=20)),
                ('tamañom', models.IntegerField()),
            ],
        ),
    ]
